{
    "created": 1731004899.0458622,
    "duration": 0.14269328117370605,
    "exitcode": 1,
    "root": "/tmp/code_dse0junw",
    "environment": {},
    "summary": {
        "failed": 4,
        "total": 4,
        "collected": 4
    },
    "collectors": [
        {
            "nodeid": "",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "test_profile.py",
                    "type": "Module"
                }
            ]
        },
        {
            "nodeid": "test_profile.py::DNAProfilerTestCase",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "test_profile.py::DNAProfilerTestCase::test_match_alice",
                    "type": "TestCaseFunction",
                    "lineno": 4
                },
                {
                    "nodeid": "test_profile.py::DNAProfilerTestCase::test_match_bob",
                    "type": "TestCaseFunction",
                    "lineno": 8
                },
                {
                    "nodeid": "test_profile.py::DNAProfilerTestCase::test_match_charlie",
                    "type": "TestCaseFunction",
                    "lineno": 12
                },
                {
                    "nodeid": "test_profile.py::DNAProfilerTestCase::test_no_match",
                    "type": "TestCaseFunction",
                    "lineno": 16
                }
            ]
        },
        {
            "nodeid": "test_profile.py",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "test_profile.py::DNAProfilerTestCase",
                    "type": "UnitTestCase"
                }
            ]
        }
    ],
    "tests": [
        {
            "nodeid": "test_profile.py::DNAProfilerTestCase::test_match_alice",
            "lineno": 4,
            "outcome": "failed",
            "keywords": [
                "test_match_alice",
                "DNAProfilerTestCase",
                "test_profile.py",
                "code_dse0junw"
            ],
            "setup": {
                "duration": 0.00017925607971847057,
                "outcome": "passed"
            },
            "call": {
                "duration": 0.015872545074671507,
                "outcome": "failed",
                "crash": {
                    "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                    "lineno": 526,
                    "message": "subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'alice.txt']' returned non-zero exit status 1."
                },
                "traceback": [
                    {
                        "path": "test_profile.py",
                        "lineno": 6,
                        "message": ""
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 421,
                        "message": "in check_output"
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 526,
                        "message": "CalledProcessError"
                    }
                ],
                "stderr": "Traceback (most recent call last):\n  File \"/tmp/code_dse0junw/profile.py\", line 53, in <module>\n    main()\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in main\n    dna_data = {key: int(value) for key, value in row.items()}\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in <dictcomp>\n    dna_data = {key: int(value) for key, value in row.items()}\nValueError: invalid literal for int() with base 10: 'Alice'\n",
                "longrepr": "self = <test_profile.DNAProfilerTestCase testMethod=test_match_alice>\n\n    def test_match_alice(self):\n>       output = subprocess.check_output([\"python\", \"profile.py\", \"data.csv\", \"alice.txt\"])\n\ntest_profile.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/brad/.miniconda3/lib/python3.10/subprocess.py:421: in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ninput = None, capture_output = False, timeout = None, check = True\npopenargs = (['python', 'profile.py', 'data.csv', 'alice.txt'],)\nkwargs = {'stdout': -1}\nprocess = <Popen: returncode: 1 args: ['python', 'profile.py', 'data.csv', 'alice.txt']>\nstdout = b'', stderr = None, retcode = 1\n\n    def run(*popenargs,\n            input=None, capture_output=False, timeout=None, check=False, **kwargs):\n        \"\"\"Run command with arguments and return a CompletedProcess instance.\n    \n        The returned instance will have attributes args, returncode, stdout and\n        stderr. By default, stdout and stderr are not captured, and those attributes\n        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,\n        or pass capture_output=True to capture both.\n    \n        If check is True and the exit code was non-zero, it raises a\n        CalledProcessError. The CalledProcessError object will have the return code\n        in the returncode attribute, and output & stderr attributes if those streams\n        were captured.\n    \n        If timeout is given, and the process takes too long, a TimeoutExpired\n        exception will be raised.\n    \n        There is an optional argument \"input\", allowing you to\n        pass bytes or a string to the subprocess's stdin.  If you use this argument\n        you may not also use the Popen constructor's \"stdin\" argument, as\n        it will be used internally.\n    \n        By default, all communication is in bytes, and therefore any \"input\" should\n        be bytes, and the stdout and stderr will be bytes. If in text mode, any\n        \"input\" should be a string, and stdout and stderr will be strings decoded\n        according to locale encoding, or by \"encoding\" if set. Text mode is\n        triggered by setting any of text, encoding, errors or universal_newlines.\n    \n        The other arguments are the same as for the Popen constructor.\n        \"\"\"\n        if input is not None:\n            if kwargs.get('stdin') is not None:\n                raise ValueError('stdin and input arguments may not both be used.')\n            kwargs['stdin'] = PIPE\n    \n        if capture_output:\n            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:\n                raise ValueError('stdout and stderr arguments may not be used '\n                                 'with capture_output.')\n            kwargs['stdout'] = PIPE\n            kwargs['stderr'] = PIPE\n    \n        with Popen(*popenargs, **kwargs) as process:\n            try:\n                stdout, stderr = process.communicate(input, timeout=timeout)\n            except TimeoutExpired as exc:\n                process.kill()\n                if _mswindows:\n                    # Windows accumulates the output in a single blocking\n                    # read() call run on child threads, with the timeout\n                    # being done in a join() on those threads.  communicate()\n                    # _after_ kill() is required to collect that and add it\n                    # to the exception.\n                    exc.stdout, exc.stderr = process.communicate()\n                else:\n                    # POSIX _communicate already populated the output so\n                    # far into the TimeoutExpired exception.\n                    process.wait()\n                raise\n            except:  # Including KeyboardInterrupt, communicate handled that.\n                process.kill()\n                # We don't call process.wait() as .__exit__ does that for us.\n                raise\n            retcode = process.poll()\n            if check and retcode:\n>               raise CalledProcessError(retcode, process.args,\n                                         output=stdout, stderr=stderr)\nE               subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'alice.txt']' returned non-zero exit status 1.\n\n/home/brad/.miniconda3/lib/python3.10/subprocess.py:526: CalledProcessError"
            },
            "teardown": {
                "duration": 9.64021310210228e-05,
                "outcome": "passed"
            }
        },
        {
            "nodeid": "test_profile.py::DNAProfilerTestCase::test_match_bob",
            "lineno": 8,
            "outcome": "failed",
            "keywords": [
                "test_match_bob",
                "DNAProfilerTestCase",
                "test_profile.py",
                "code_dse0junw"
            ],
            "setup": {
                "duration": 9.24370251595974e-05,
                "outcome": "passed"
            },
            "call": {
                "duration": 0.017461554845795035,
                "outcome": "failed",
                "crash": {
                    "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                    "lineno": 526,
                    "message": "subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'bob.txt']' returned non-zero exit status 1."
                },
                "traceback": [
                    {
                        "path": "test_profile.py",
                        "lineno": 10,
                        "message": ""
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 421,
                        "message": "in check_output"
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 526,
                        "message": "CalledProcessError"
                    }
                ],
                "stderr": "Traceback (most recent call last):\n  File \"/tmp/code_dse0junw/profile.py\", line 53, in <module>\n    main()\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in main\n    dna_data = {key: int(value) for key, value in row.items()}\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in <dictcomp>\n    dna_data = {key: int(value) for key, value in row.items()}\nValueError: invalid literal for int() with base 10: 'Alice'\n",
                "longrepr": "self = <test_profile.DNAProfilerTestCase testMethod=test_match_bob>\n\n    def test_match_bob(self):\n>       output = subprocess.check_output([\"python\", \"profile.py\", \"data.csv\", \"bob.txt\"])\n\ntest_profile.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/brad/.miniconda3/lib/python3.10/subprocess.py:421: in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ninput = None, capture_output = False, timeout = None, check = True\npopenargs = (['python', 'profile.py', 'data.csv', 'bob.txt'],)\nkwargs = {'stdout': -1}\nprocess = <Popen: returncode: 1 args: ['python', 'profile.py', 'data.csv', 'bob.txt']>\nstdout = b'', stderr = None, retcode = 1\n\n    def run(*popenargs,\n            input=None, capture_output=False, timeout=None, check=False, **kwargs):\n        \"\"\"Run command with arguments and return a CompletedProcess instance.\n    \n        The returned instance will have attributes args, returncode, stdout and\n        stderr. By default, stdout and stderr are not captured, and those attributes\n        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,\n        or pass capture_output=True to capture both.\n    \n        If check is True and the exit code was non-zero, it raises a\n        CalledProcessError. The CalledProcessError object will have the return code\n        in the returncode attribute, and output & stderr attributes if those streams\n        were captured.\n    \n        If timeout is given, and the process takes too long, a TimeoutExpired\n        exception will be raised.\n    \n        There is an optional argument \"input\", allowing you to\n        pass bytes or a string to the subprocess's stdin.  If you use this argument\n        you may not also use the Popen constructor's \"stdin\" argument, as\n        it will be used internally.\n    \n        By default, all communication is in bytes, and therefore any \"input\" should\n        be bytes, and the stdout and stderr will be bytes. If in text mode, any\n        \"input\" should be a string, and stdout and stderr will be strings decoded\n        according to locale encoding, or by \"encoding\" if set. Text mode is\n        triggered by setting any of text, encoding, errors or universal_newlines.\n    \n        The other arguments are the same as for the Popen constructor.\n        \"\"\"\n        if input is not None:\n            if kwargs.get('stdin') is not None:\n                raise ValueError('stdin and input arguments may not both be used.')\n            kwargs['stdin'] = PIPE\n    \n        if capture_output:\n            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:\n                raise ValueError('stdout and stderr arguments may not be used '\n                                 'with capture_output.')\n            kwargs['stdout'] = PIPE\n            kwargs['stderr'] = PIPE\n    \n        with Popen(*popenargs, **kwargs) as process:\n            try:\n                stdout, stderr = process.communicate(input, timeout=timeout)\n            except TimeoutExpired as exc:\n                process.kill()\n                if _mswindows:\n                    # Windows accumulates the output in a single blocking\n                    # read() call run on child threads, with the timeout\n                    # being done in a join() on those threads.  communicate()\n                    # _after_ kill() is required to collect that and add it\n                    # to the exception.\n                    exc.stdout, exc.stderr = process.communicate()\n                else:\n                    # POSIX _communicate already populated the output so\n                    # far into the TimeoutExpired exception.\n                    process.wait()\n                raise\n            except:  # Including KeyboardInterrupt, communicate handled that.\n                process.kill()\n                # We don't call process.wait() as .__exit__ does that for us.\n                raise\n            retcode = process.poll()\n            if check and retcode:\n>               raise CalledProcessError(retcode, process.args,\n                                         output=stdout, stderr=stderr)\nE               subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'bob.txt']' returned non-zero exit status 1.\n\n/home/brad/.miniconda3/lib/python3.10/subprocess.py:526: CalledProcessError"
            },
            "teardown": {
                "duration": 0.00010001100599765778,
                "outcome": "passed"
            }
        },
        {
            "nodeid": "test_profile.py::DNAProfilerTestCase::test_match_charlie",
            "lineno": 12,
            "outcome": "failed",
            "keywords": [
                "test_match_charlie",
                "DNAProfilerTestCase",
                "test_profile.py",
                "code_dse0junw"
            ],
            "setup": {
                "duration": 8.672801777720451e-05,
                "outcome": "passed"
            },
            "call": {
                "duration": 0.01909500313922763,
                "outcome": "failed",
                "crash": {
                    "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                    "lineno": 526,
                    "message": "subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'charlie.txt']' returned non-zero exit status 1."
                },
                "traceback": [
                    {
                        "path": "test_profile.py",
                        "lineno": 14,
                        "message": ""
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 421,
                        "message": "in check_output"
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 526,
                        "message": "CalledProcessError"
                    }
                ],
                "stderr": "Traceback (most recent call last):\n  File \"/tmp/code_dse0junw/profile.py\", line 53, in <module>\n    main()\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in main\n    dna_data = {key: int(value) for key, value in row.items()}\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in <dictcomp>\n    dna_data = {key: int(value) for key, value in row.items()}\nValueError: invalid literal for int() with base 10: 'Alice'\n",
                "longrepr": "self = <test_profile.DNAProfilerTestCase testMethod=test_match_charlie>\n\n    def test_match_charlie(self):\n>       output = subprocess.check_output([\"python\", \"profile.py\", \"data.csv\", \"charlie.txt\"])\n\ntest_profile.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/brad/.miniconda3/lib/python3.10/subprocess.py:421: in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ninput = None, capture_output = False, timeout = None, check = True\npopenargs = (['python', 'profile.py', 'data.csv', 'charlie.txt'],)\nkwargs = {'stdout': -1}\nprocess = <Popen: returncode: 1 args: ['python', 'profile.py', 'data.csv', 'charlie.txt']>\nstdout = b'', stderr = None, retcode = 1\n\n    def run(*popenargs,\n            input=None, capture_output=False, timeout=None, check=False, **kwargs):\n        \"\"\"Run command with arguments and return a CompletedProcess instance.\n    \n        The returned instance will have attributes args, returncode, stdout and\n        stderr. By default, stdout and stderr are not captured, and those attributes\n        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,\n        or pass capture_output=True to capture both.\n    \n        If check is True and the exit code was non-zero, it raises a\n        CalledProcessError. The CalledProcessError object will have the return code\n        in the returncode attribute, and output & stderr attributes if those streams\n        were captured.\n    \n        If timeout is given, and the process takes too long, a TimeoutExpired\n        exception will be raised.\n    \n        There is an optional argument \"input\", allowing you to\n        pass bytes or a string to the subprocess's stdin.  If you use this argument\n        you may not also use the Popen constructor's \"stdin\" argument, as\n        it will be used internally.\n    \n        By default, all communication is in bytes, and therefore any \"input\" should\n        be bytes, and the stdout and stderr will be bytes. If in text mode, any\n        \"input\" should be a string, and stdout and stderr will be strings decoded\n        according to locale encoding, or by \"encoding\" if set. Text mode is\n        triggered by setting any of text, encoding, errors or universal_newlines.\n    \n        The other arguments are the same as for the Popen constructor.\n        \"\"\"\n        if input is not None:\n            if kwargs.get('stdin') is not None:\n                raise ValueError('stdin and input arguments may not both be used.')\n            kwargs['stdin'] = PIPE\n    \n        if capture_output:\n            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:\n                raise ValueError('stdout and stderr arguments may not be used '\n                                 'with capture_output.')\n            kwargs['stdout'] = PIPE\n            kwargs['stderr'] = PIPE\n    \n        with Popen(*popenargs, **kwargs) as process:\n            try:\n                stdout, stderr = process.communicate(input, timeout=timeout)\n            except TimeoutExpired as exc:\n                process.kill()\n                if _mswindows:\n                    # Windows accumulates the output in a single blocking\n                    # read() call run on child threads, with the timeout\n                    # being done in a join() on those threads.  communicate()\n                    # _after_ kill() is required to collect that and add it\n                    # to the exception.\n                    exc.stdout, exc.stderr = process.communicate()\n                else:\n                    # POSIX _communicate already populated the output so\n                    # far into the TimeoutExpired exception.\n                    process.wait()\n                raise\n            except:  # Including KeyboardInterrupt, communicate handled that.\n                process.kill()\n                # We don't call process.wait() as .__exit__ does that for us.\n                raise\n            retcode = process.poll()\n            if check and retcode:\n>               raise CalledProcessError(retcode, process.args,\n                                         output=stdout, stderr=stderr)\nE               subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'charlie.txt']' returned non-zero exit status 1.\n\n/home/brad/.miniconda3/lib/python3.10/subprocess.py:526: CalledProcessError"
            },
            "teardown": {
                "duration": 9.96601302176714e-05,
                "outcome": "passed"
            }
        },
        {
            "nodeid": "test_profile.py::DNAProfilerTestCase::test_no_match",
            "lineno": 16,
            "outcome": "failed",
            "keywords": [
                "test_no_match",
                "DNAProfilerTestCase",
                "test_profile.py",
                "code_dse0junw"
            ],
            "setup": {
                "duration": 0.00010225502774119377,
                "outcome": "passed"
            },
            "call": {
                "duration": 0.0183170260861516,
                "outcome": "failed",
                "crash": {
                    "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                    "lineno": 526,
                    "message": "subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'nomatch.txt']' returned non-zero exit status 1."
                },
                "traceback": [
                    {
                        "path": "test_profile.py",
                        "lineno": 18,
                        "message": ""
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 421,
                        "message": "in check_output"
                    },
                    {
                        "path": "/home/brad/.miniconda3/lib/python3.10/subprocess.py",
                        "lineno": 526,
                        "message": "CalledProcessError"
                    }
                ],
                "stderr": "Traceback (most recent call last):\n  File \"/tmp/code_dse0junw/profile.py\", line 53, in <module>\n    main()\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in main\n    dna_data = {key: int(value) for key, value in row.items()}\n  File \"/tmp/code_dse0junw/profile.py\", line 16, in <dictcomp>\n    dna_data = {key: int(value) for key, value in row.items()}\nValueError: invalid literal for int() with base 10: 'Alice'\n",
                "longrepr": "self = <test_profile.DNAProfilerTestCase testMethod=test_no_match>\n\n    def test_no_match(self):\n>       output = subprocess.check_output([\"python\", \"profile.py\", \"data.csv\", \"nomatch.txt\"])\n\ntest_profile.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/brad/.miniconda3/lib/python3.10/subprocess.py:421: in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ninput = None, capture_output = False, timeout = None, check = True\npopenargs = (['python', 'profile.py', 'data.csv', 'nomatch.txt'],)\nkwargs = {'stdout': -1}\nprocess = <Popen: returncode: 1 args: ['python', 'profile.py', 'data.csv', 'nomatch.txt']>\nstdout = b'', stderr = None, retcode = 1\n\n    def run(*popenargs,\n            input=None, capture_output=False, timeout=None, check=False, **kwargs):\n        \"\"\"Run command with arguments and return a CompletedProcess instance.\n    \n        The returned instance will have attributes args, returncode, stdout and\n        stderr. By default, stdout and stderr are not captured, and those attributes\n        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,\n        or pass capture_output=True to capture both.\n    \n        If check is True and the exit code was non-zero, it raises a\n        CalledProcessError. The CalledProcessError object will have the return code\n        in the returncode attribute, and output & stderr attributes if those streams\n        were captured.\n    \n        If timeout is given, and the process takes too long, a TimeoutExpired\n        exception will be raised.\n    \n        There is an optional argument \"input\", allowing you to\n        pass bytes or a string to the subprocess's stdin.  If you use this argument\n        you may not also use the Popen constructor's \"stdin\" argument, as\n        it will be used internally.\n    \n        By default, all communication is in bytes, and therefore any \"input\" should\n        be bytes, and the stdout and stderr will be bytes. If in text mode, any\n        \"input\" should be a string, and stdout and stderr will be strings decoded\n        according to locale encoding, or by \"encoding\" if set. Text mode is\n        triggered by setting any of text, encoding, errors or universal_newlines.\n    \n        The other arguments are the same as for the Popen constructor.\n        \"\"\"\n        if input is not None:\n            if kwargs.get('stdin') is not None:\n                raise ValueError('stdin and input arguments may not both be used.')\n            kwargs['stdin'] = PIPE\n    \n        if capture_output:\n            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:\n                raise ValueError('stdout and stderr arguments may not be used '\n                                 'with capture_output.')\n            kwargs['stdout'] = PIPE\n            kwargs['stderr'] = PIPE\n    \n        with Popen(*popenargs, **kwargs) as process:\n            try:\n                stdout, stderr = process.communicate(input, timeout=timeout)\n            except TimeoutExpired as exc:\n                process.kill()\n                if _mswindows:\n                    # Windows accumulates the output in a single blocking\n                    # read() call run on child threads, with the timeout\n                    # being done in a join() on those threads.  communicate()\n                    # _after_ kill() is required to collect that and add it\n                    # to the exception.\n                    exc.stdout, exc.stderr = process.communicate()\n                else:\n                    # POSIX _communicate already populated the output so\n                    # far into the TimeoutExpired exception.\n                    process.wait()\n                raise\n            except:  # Including KeyboardInterrupt, communicate handled that.\n                process.kill()\n                # We don't call process.wait() as .__exit__ does that for us.\n                raise\n            retcode = process.poll()\n            if check and retcode:\n>               raise CalledProcessError(retcode, process.args,\n                                         output=stdout, stderr=stderr)\nE               subprocess.CalledProcessError: Command '['python', 'profile.py', 'data.csv', 'nomatch.txt']' returned non-zero exit status 1.\n\n/home/brad/.miniconda3/lib/python3.10/subprocess.py:526: CalledProcessError"
            },
            "teardown": {
                "duration": 0.00014206720516085625,
                "outcome": "passed"
            }
        }
    ]
}